name: branch_checkout
on: [push]
jobs:
  external-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
      - uses: actions/checkout
        with:
          ref: abystoma/external-workflow@branch
        run: echo "$(<greetings.txt)"