name: branch_checkout
on: [push]
jobs:
  external-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
        with:
          repository: abystoma/external-workflow@v3
          ref: branch
      - name: Greetings
        run: echo "$(<greetings.txt)"